# Generated by Django 3.1.3 on 2020-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordem_Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('causa', models.TextField(help_text='Causa do ProBlema')),
                ('realizado', models.TextField(help_text='Serviço Realizado')),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(help_text='Nome do Setor da Empresa', max_length=100)),
                ('centro_custo', models.CharField(help_text='Centro de custo do Setor', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(help_text='Tipo do Serviço', max_length=100)),
                ('descricao', models.TextField(help_text='Descrição do Tipo de Serviço')),
            ],
        ),
    ]
