# Generated by Django 3.1.3 on 2020-11-17 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordem_servico', '0004_student2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Student2',
        ),
    ]
