# Generated by Django 3.1.3 on 2020-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almoxarifado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da Peça', max_length=100)),
                ('descricao', models.TextField(help_text='Descrição da Peça')),
            ],
        ),
    ]
